FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV GENERIC_TIMEZONE=America/Sao_Paulo

# Postgres (Radar Comercial Railway project)
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=trolley.proxy.rlwy.net
ENV DB_POSTGRESDB_PORT=43752
ENV DB_POSTGRESDB_DATABASE=railway
ENV DB_POSTGRESDB_USER=postgres
ENV DB_POSTGRESDB_PASSWORD=lRlwlACgqRkNKoNWCdiSxtIlGRAAXUjg
ENV DB_POSTGRESDB_SSL_ENABLED=true
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
